# Generated by Django 3.0.7 on 2020-07-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('artista_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('genero', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='femenino', max_length=15)),
                ('correo', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('cancion_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=70)),
                ('tipoCancion', models.CharField(choices=[('Salsa', 'salsa'), ('rock', 'rock'), ('electronica', 'electronica')], default='rock', max_length=30)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Artista')),
            ],
        ),
    ]
